#!/usr/bin/env bash
#Displays the content of the current directory in a list format
#Only the part of the name with first dash is displayed
list=$(ls)
for i in $list;
do
echo "$i" | cut -d '-' -f2
done
